version: '3.7'
services:
  mongo:
    image: mongo:4.1.6
    volumes:
      - ./mongo-config:/docker-entrypoint-initdb.d
      - /var/lib/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root2019
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - 27017:27017
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - ecommerce_cluster

  mongo-express:
    image: mongo-express:0.49
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root2019
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - ecommerce_cluster

  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: nimda
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - ecommerce_cluster

  ms-iam:
    image: ms-iam:latest
    ports:
      - 8094:8094
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-stores:
    image: ms-stores:latest
    ports:
      - 8090:8090
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-orders:
    image: ms-orders:latest
    ports:
      - 8091:8091
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-orders-consumer:
    image: ms-orders-consumer:latest
    ports:
      - 8092:8092
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-orders
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-payments:
    image: ms-payments:latest
    ports:
      - 8093:8093
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

networks:
  ecommerce_cluster:
    driver: overlay #bridge