version: '3.7'
services:
  mongo:
    image: mongo:4.1.6
    volumes:
      - ./mongo-config:/docker-entrypoint-initdb.d
      - /var/lib/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root2019
      MONGO_INITDB_DATABASE: ecommerce
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - ecommerce_cluster

  mongo-express:
    image: mongo-express:0.49
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root2019
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - ecommerce_cluster

  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: nimda
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - ecommerce_cluster

  ms-iam:
    image: ms-iam:latest
    ports:
      - target: 8094
        published: 8094
        protocol: tcp
        mode: host
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-stores:
    image: ms-stores:latest
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
        mode: host
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-orders:
    image: ms-orders:latest
    ports:
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-orders-consumer:
    image: ms-orders-consumer:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    depends_on:
      - ms-orders
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

  ms-payments:
    image: ms-payments:latest
    ports:
      - target: 8093
        published: 8093
        protocol: tcp
        mode: host
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - ecommerce_cluster

networks:
  ecommerce_cluster:
    driver: overlay