FROM openjdk:8u191-jre-alpine3.8

ENV HOME=/home/ms-orders

WORKDIR $HOME

RUN apk add --no-cache bash; \
    apk add netcat-openbsd

# https://github.com/vishnubob/wait-for-it
ADD wait-for.sh wait-for.sh

ADD ms-orders/build/libs/ms-orders.jar ms-orders.jar