server:
  port: 8091

spring:
  application:
    name: ms-ordersconsumer
  data.mongodb:
    host: mongo
    port: 27017
    username: app
    password: app2019
    database: ecommerce
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: nimda

rabbitmq:
  order:
    queue.name: OrderQueue
    exchange.name: OrderExchange
    routingKey.name: OrderRoutingKey