server:
  port: 8094
  http2.enabled: true
  compression.enabled: true
  compression.mime-types: application/json
  compression.min-response-size: 1024

spring:
  application:
    name: ms-iam
  data.mongodb:
    host: localhost
    port: 27017
    username: app
    password: app2019
    database: ecommerce
  security:
    expirationTime: 3600000 #1h